#!/usr/bin/env bash
set -euo pipefail

# Generate a Supabase .env (interactive, does not print secrets)
#
# Modes:
# - Minimal mode (default): generates a minimal .env containing only the non-overlapping keys
#   this script controls.
# - Base-env mode (recommended): updates an existing (upstream) supabase docker .env in-place,
#   preserving all other keys.
#
# Usage:
#   scripts/generate_supabase_env.sh [--non-interactive] [--base-env PATH] [--output PATH]

OUT_PATH=".env"
BASE_ENV=""
OUTPUT_PROVIDED=0
NONINTERACTIVE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --non-interactive) NONINTERACTIVE=1; shift ;;
    --base-env) BASE_ENV="$2"; shift 2 ;;
    --output) OUT_PATH="$2"; OUTPUT_PROVIDED=1; shift 2 ;;
    --help)
      echo "Usage: $0 [--non-interactive] [--base-env PATH] [--output PATH]";
      echo "Examples:";
      echo "  $0 --base-env supabase-project/.env --output supabase-project/.env";
      echo "  $0 --output supabase-project/.env";
      exit 0 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

ask() {
  local prompt="$1" default="${2:-}"
  if [ "$NONINTERACTIVE" -eq 1 ]; then
    printf "%s" "$default"
  else
    if [ -n "$default" ]; then
      read -r -p "$prompt [$default]: " val
      val="${val:-$default}"
    else
      read -r -p "$prompt: " val
    fi
    printf "%s" "$val"
  fi
}

gen_base64() { openssl rand -base64 "$1" 2>/dev/null || head -c "$1" /dev/urandom | base64; }
gen_hex() { openssl rand -hex "$1" 2>/dev/null || head -c "$(( $1 * 2 ))" /dev/urandom | xxd -p -c 200; }

normalize_url() {
  local url="$1"
  if [[ -z "$url" ]]; then
    printf '%s' "$url"
    return
  fi
  if [[ "$url" =~ ^https:// ]]; then
    printf '%s' "$url"
    return
  fi
  if [[ "$url" =~ ^http:// ]]; then
    printf 'https://%s' "${url#http://}"
    return
  fi
  printf 'https://%s' "$url"
}

update_env_key() {
  local file="$1" key="$2" value="$3"
  local tmp
  tmp="$(mktemp)"

  local found=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$line" =~ ^(export[[:space:]]+)?${key}= ]]; then
      if [[ "$line" =~ ^export[[:space:]]+ ]]; then
        printf 'export %s=%s\n' "$key" "$value" >> "$tmp"
      else
        printf '%s=%s\n' "$key" "$value" >> "$tmp"
      fi
      found=1
    else
      printf '%s\n' "$line" >> "$tmp"
    fi
  done < "$file"

  if [[ "$found" -eq 0 ]]; then
    printf '%s=%s\n' "$key" "$value" >> "$tmp"
  fi

  mv "$tmp" "$file"
}

if [[ -n "$BASE_ENV" ]]; then
  if [[ ! -f "$BASE_ENV" ]]; then
    echo "ERROR: --base-env file not found: $BASE_ENV" >&2
    exit 1
  fi
  if [[ "$OUTPUT_PROVIDED" -eq 0 ]]; then
    OUT_PATH="$BASE_ENV"
  fi
fi

echo "Generating Supabase .env -> $OUT_PATH"

# Collect values
SUPABASE_PUBLIC_URL=$(ask "External HTTPS base URL (SUPABASE_PUBLIC_URL, will add https:// if missing)" "https://example.com")
SUPABASE_PUBLIC_URL=$(normalize_url "$SUPABASE_PUBLIC_URL")

API_EXTERNAL_URL=$(ask "API_EXTERNAL_URL (leave empty to use SUPABASE_PUBLIC_URL)" "$SUPABASE_PUBLIC_URL")
if [[ -n "$API_EXTERNAL_URL" ]]; then
  API_EXTERNAL_URL=$(normalize_url "$API_EXTERNAL_URL")
else
  API_EXTERNAL_URL="$SUPABASE_PUBLIC_URL"
fi
SITE_URL=$(ask "SITE_URL (leave empty to use SUPABASE_PUBLIC_URL)" "$SUPABASE_PUBLIC_URL")
if [[ -n "$SITE_URL" ]]; then
  SITE_URL=$(normalize_url "$SITE_URL")
else
  SITE_URL="$SUPABASE_PUBLIC_URL"
fi

POSTGRES_PASSWORD_CHOICE=$(ask "Provide Postgres password or type 'generate' to create one" "generate")
if [ "$POSTGRES_PASSWORD_CHOICE" = "generate" ]; then
  POSTGRES_PASSWORD=$(gen_hex 16)
else
  POSTGRES_PASSWORD="$POSTGRES_PASSWORD_CHOICE"
fi

# Dashboard creds
DASHBOARD_USERNAME=$(ask "Dashboard username" "admin")
DASHBOARD_PASSWORD_CHOICE=$(ask "Dashboard password (or 'generate')" "generate")
if [ "$DASHBOARD_PASSWORD_CHOICE" = "generate" ]; then
  DASHBOARD_PASSWORD=$(gen_base64 32)
else
  DASHBOARD_PASSWORD="$DASHBOARD_PASSWORD_CHOICE"
fi

# Non-overlapping secrets (generate)
echo "Generating non-overlapping secrets (secrets will not be printed)."
MINIO_ROOT_PASSWORD=$(gen_hex 16)

# Build/write .env (do not echo values)
mkdir -p "$(dirname "$OUT_PATH")" 2>/dev/null || true

if [[ -n "$BASE_ENV" ]]; then
  # Preserve all keys from the upstream docker .env and only override the ones
  # this script controls.
  if [[ "$OUT_PATH" != "$BASE_ENV" ]]; then
    cp "$BASE_ENV" "$OUT_PATH"
  fi

  update_env_key "$OUT_PATH" "POSTGRES_PASSWORD" "$POSTGRES_PASSWORD"
  update_env_key "$OUT_PATH" "SUPABASE_PUBLIC_URL" "$SUPABASE_PUBLIC_URL"
  update_env_key "$OUT_PATH" "API_EXTERNAL_URL" "$API_EXTERNAL_URL"
  update_env_key "$OUT_PATH" "SITE_URL" "$SITE_URL"
  update_env_key "$OUT_PATH" "DASHBOARD_USERNAME" "$DASHBOARD_USERNAME"
  update_env_key "$OUT_PATH" "DASHBOARD_PASSWORD" "$DASHBOARD_PASSWORD"

  update_env_key "$OUT_PATH" "MINIO_ROOT_PASSWORD" "$MINIO_ROOT_PASSWORD"
  update_env_key "$OUT_PATH" "FUNCTIONS_VERIFY_JWT" "true"
else
  {
    cat <<EOF
# Supabase .env generated by scripts/generate_supabase_env.sh
POSTGRES_DB=db
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

SUPABASE_PUBLIC_URL=$SUPABASE_PUBLIC_URL
API_EXTERNAL_URL=$API_EXTERNAL_URL
SITE_URL=$SITE_URL

DASHBOARD_USERNAME=$DASHBOARD_USERNAME
DASHBOARD_PASSWORD=$DASHBOARD_PASSWORD

MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD

# Functions
FUNCTIONS_VERIFY_JWT=true

EOF
  } > "$OUT_PATH"
fi

# Secure file
chmod 600 "$OUT_PATH"

echo "Wrote $OUT_PATH (secrets were generated and NOT printed)."
echo "Keep this file private. Example: chmod 600 $OUT_PATH"
echo "Next steps: run ./utils/generate-keys.sh for auth/internal keys, then docker compose pull && docker compose up -d"

exit 0
