#!/usr/bin/env bash
set -euo pipefail

# Generate a supabase .env file (interactive, does not print secrets)
# Usage: scripts/generate_supabase_env.sh [--non-interactive] [--output ./supabase-project/.env]

OUT_PATH=".env"
NONINTERACTIVE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --non-interactive) NONINTERACTIVE=1; shift ;;
    --output) OUT_PATH="$2"; shift 2 ;;
    --help) echo "Usage: $0 [--non-interactive] [--output PATH]"; exit 0 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

ask() {
  local prompt="$1" default="${2:-}"
  if [ "$NONINTERACTIVE" -eq 1 ]; then
    printf "%s" "$default"
  else
    if [ -n "$default" ]; then
      read -r -p "$prompt [$default]: " val
      val="${val:-$default}"
    else
      read -r -p "$prompt: " val
    fi
    printf "%s" "$val"
  fi
}

gen_base64() { openssl rand -base64 "$1" 2>/dev/null || head -c "$1" /dev/urandom | base64; }
gen_hex() { openssl rand -hex "$1" 2>/dev/null || head -c "$(( $1 * 2 ))" /dev/urandom | xxd -p -c 200; }

echo "Generating Supabase .env -> $OUT_PATH"

# Collect values
SUPABASE_PUBLIC_URL=$(ask "External HTTPS base URL (SUPABASE_PUBLIC_URL, must start with https://)" "https://example.com")
if [[ "$SUPABASE_PUBLIC_URL" != https://* ]]; then
  echo "ERROR: SUPABASE_PUBLIC_URL must start with https://" >&2
  exit 1
fi

API_EXTERNAL_URL=$(ask "API_EXTERNAL_URL (leave empty to use SUPABASE_PUBLIC_URL)" "$SUPABASE_PUBLIC_URL")
SITE_URL=$(ask "SITE_URL (leave empty to use SUPABASE_PUBLIC_URL)" "$SUPABASE_PUBLIC_URL")

POSTGRES_PASSWORD_CHOICE=$(ask "Provide Postgres password or type 'generate' to create one" "generate")
if [ "$POSTGRES_PASSWORD_CHOICE" = "generate" ]; then
  POSTGRES_PASSWORD=$(gen_hex 16)
else
  POSTGRES_PASSWORD="$POSTGRES_PASSWORD_CHOICE"
fi

# Dashboard creds
DASHBOARD_USERNAME=$(ask "Dashboard username" "admin")
DASHBOARD_PASSWORD_CHOICE=$(ask "Dashboard password (or 'generate')" "generate")
if [ "$DASHBOARD_PASSWORD_CHOICE" = "generate" ]; then
  DASHBOARD_PASSWORD=$(gen_base64 32)
else
  DASHBOARD_PASSWORD="$DASHBOARD_PASSWORD_CHOICE"
fi

# Secrets (generate)
echo "Generating cryptographic keys (secrets will not be printed)."
JWT_SECRET=$(gen_base64 48)
ANON_KEY=$(gen_base64 48)
SERVICE_ROLE_KEY=$(gen_base64 48)
SECRET_KEY_BASE=$(gen_base64 48)
VAULT_ENC_KEY=$(gen_hex 16)
PG_META_CRYPTO_KEY=$(gen_base64 24)
MINIO_ROOT_PASSWORD=$(gen_hex 16)

# Build .env content (do not echo values)
mkdir -p "$(dirname "$OUT_PATH")" 2>/dev/null || true
{
  cat <<EOF
# Supabase .env generated by scripts/generate_supabase_env.sh
POSTGRES_DB=db
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

JWT_SECRET=$JWT_SECRET
ANON_KEY=$ANON_KEY
SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY

SECRET_KEY_BASE=$SECRET_KEY_BASE
VAULT_ENC_KEY=$VAULT_ENC_KEY
PG_META_CRYPTO_KEY=$PG_META_CRYPTO_KEY

SUPABASE_PUBLIC_URL=$SUPABASE_PUBLIC_URL
API_EXTERNAL_URL=$API_EXTERNAL_URL
SITE_URL=$SITE_URL

DASHBOARD_USERNAME=$DASHBOARD_USERNAME
DASHBOARD_PASSWORD=$DASHBOARD_PASSWORD

MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD

# Functions
FUNCTIONS_VERIFY_JWT=true

EOF
} > "$OUT_PATH"

# Secure file
chmod 600 "$OUT_PATH"

echo "Wrote $OUT_PATH (secrets were generated and NOT printed)."
echo "Keep this file private. Example: chmod 600 $OUT_PATH"
echo "Next steps: edit any optional values, then run: docker compose pull && docker compose up -d"

exit 0
